//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoEstatal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public string emCedula { get; set; }
        public string emNombre { get; set; }
        public string emApellido { get; set; }
        public string emCorreo { get; set; }
        public string emDireccion { get; set; }
        public string emTelefono { get; set; }
        public byte[] emFoto { get; set; }
        public Nullable<int> emGenero_fk { get; set; }
        public Nullable<int> emCargos_fk { get; set; }
        public Nullable<int> emSedes_fk { get; set; }
    
        public virtual cargos cargos { get; set; }
        public virtual generos generos { get; set; }
        public virtual sedes sedes { get; set; }
    }
}
